import { ColorsTypes } from "../types/ColorsTypes";

const lightThemeColors: ColorsTypes = {
    PRIMARY: "#c29d3c",
    SECONDARY: "#797979",

    PRIMARY_TEXT: "#242424",
    SECONDARY_TEXT: "#797979",
    ERROR_TEXT: "#FF0000",
    BUTTON_TEXT: "#FFFFFF",

    PRIMARY_BACKGROUND: "#F9F9F9",
    SECONDARY_BACKGROUND: "#FFFFFF",
    PRIMARY_LIGHT_BACKGROUND: "#F2ECDE",

    PRIMARY_ICON: "#c29d3c",
    SECONDARY_ICON: "#242424",
    WHITE_ICON: "#FFFFFF",
    SECONDARY_LIGHT_ICON: "#797979",

    BOX_BORDER: "#DFDFDF",
    BOX_DARK_BORDER: "#AEAEB2",
    BOX_PRIMARY_BACKGROUND: "#EBEBEB",
    BOX_SECONDARY_BACKGROUND: "#F2F2F2",
    BOX_BORDER_PRIMARY: "#c29d3c",

    SHADOW_1: "rgba(194, 157, 60, 0.2)",
    SHADOW_2: "rgba(0, 0, 0, 0.5)",
    ITEM_SEPRATOR_COLOR: "#D2D2D2",

     TRANSPARENT: "#00000000",

    DISABLE_BUTTON: "#999999",
};

export { lightThemeColors }
