export const AppStrings = {
   cancel:"Cancel",
   ok:"Ok",
   signin:"Sign In",
   username:"Username",
   password:"Password",
   login:"Login",
   newuser:"New User?",
   please_input_your_email:"Please input your email!",
   please_input_your_password:"Please input your password!",
   verify_yourself:"Verify Yourself!",
   submit:"Submit",
   goback:"Go Back",
   dashboard:"Dashboard",
   transaction:"Transaction",
   payment:"Payment",
   reciept:"Reciept",
   sale:"Sale",
   sales:"Sales",
   items:"Items",
   account:"Account",
   master:"Master",
   settings:"Settings",
   reports:"Reports",
   item:"Item",
   groups:"Groups",
   customers:"Customers",
   vendors:"Vendors",
   roles:"Roles",
   users:"Users",
   add_account:"Add Account",
   user_activities:"User Activities",
   customer_ledger:"Customer Ledger",
   //SaleScreen
   add_item:"Add Item",
   add_item_modal_placeHolder:{
      name:"Name",
      itemName:"Item Name",
      group:"Group/Category",
      select_group:'Select Group',
      prefix:"Prefix",
      item_prefix:"Item Prefix",
      labour_upon:"Labour upon",
      select_labour_upon:"Select upon",
      unit:"Unit",
      select_unit:"Select Unit",
      stock_method:"Stock Method",
      select_stock_method:"Select Method",
      induvidual_price:"Individual Price ($)",
      item_price:"Item Price"
   },

   error_constants:{
     please_enter_group_name: "Please input group name!",
     item_group:"Item group",
     please_enter_input_prefix:"Please input Item prefix",
     please_select_unit:"Please select unit",
     please_select_labour_upon:"Please select Labour upon",
     please_select_stock_method:"Please select stock method"
   },

   select_unit:"Select Unit",
   labour_units:"Labour units",
   opening_balance_amount:"OPENING BALANCE AMOUNT",

   date: "Date",
   billNo: "Bill No.",
   group: 'Group',
   series: 'Series',
   accountPlaceHolder: "Select account",
   seriesPlaceHolder: "Series",
   groupPlaceHolder: "Item Group",
   billPlaceHolder: "25630",
   please_add_account: "Please add account",
   please_select_date: "Please select date",
   goodsDeliver:"Good's deliver",
   finalVoucher: "Final Voucher",
   gold_fine:"Gold fine",
   silver_fine:"Silver fine",
   amount:"Amount",
   are_you_sure:"Are you sure?",
   are_you_delete_Item:"Are you really want to delete a item?",
   are_you_really_want_logout:"Are you really want to Log out?",
   logOut:"Logout",
   item_name:"Item Name",
   stamp:"Stamp",
   add_payment_model_placeholder: {
      panels: 'Panels',
      select_panel: 'Select Panel',
      method: 'Method',
      amt_gr_wt: 'Gr.Wt.',
      default_price: '0.000',
      zero_price: '0',
      tunch: 'Tunch',
      fine: 'Fine',
      rate: 'Rate',
      Total: 'Total',
      wstg:"Wstg",
      lbr:"Lbr"
   },
   payment_details:"Payment Details",
   error:"Error",
   something_went_wrong:"Something went wrong",
   itemDetails:"Item Detail",
   contact_no:"Contact No",
   alternate_contact_no:"Alternate Contact No",
   date_of_birth:"Date of birth",
   address:"Address",
   enter_your_address:"Enter your address",
   addAccountErrorMessage:{
      please_select_your_group:"Please select your group",
      please_enter_shop_name:"Please enter a shop name!",
      please_input_your_contact_no:"Please input your contact number!",
      please_give_your_address:"Please give your address",
      customer_ledger:"Customer Ledger"
   },
   start_date:"Start Date",
   end_date:"End Date",
   summary:"Summary",
   opening_gold:"Opening Gold",
   closing_gold:"Closing Gold",
   opening_balance:"Opening Balance",
   closing_balance:"Closing Balance",
   balance:"Balance",
   sub_total:"Sub-Total",
   adjustment:"Adjustment",
   total:"Total($)",
   add_payment:"Add Payment",
   save:"Save"
};
