export const Icons = {
    DASHBOARD:require('../assets/icons/dashboard.png'),
    DROPDOWNICONS:require('../assets/icons/dropdownItemIcon.png'),
    CLOSEICON:require('../assets/icons/closeIcon.png'),
    RADIO_BUTTON_ICON: require('../assets/icons/radioButton.png'),
    SELECTED_RADIO_BUTTON_ICON: require('../assets/icons/selectedRadioButton.png'),
    SEARCH_ICON:require('../assets/icons/searchIcon.png'),
    MENU_ICON: require('../assets/icons/menu.png'),
    PLUS_ICON:require('../assets/icons/plus_icon.png'),
    CHECKBOX:require('../assets/icons/CheckBox.png'),
    UPDATEICONS:require('../assets/icons/updateIcon.png'),
    DELETEICONS:require('../assets/icons/deleteIcon.png'),
    BACKICON:require('../assets/icons/leftArrow.png'),
    QUICKACTIONBTN:require('../assets/icons/quick_add.png'),
    USERPROFILE:require('../assets/icons/profileIcon.png'),
    TRANSACTIONICON:require('../assets/icons/transaction.png'),
    SALEICON:require('../assets/icons/sale.png'),
    PAYMENTICON:require('../assets/icons/payment.png'),
    RECEIPTICON:require('../assets/icons/receipt.png'),
    MASTERICON:require('../assets/icons/master.png'),
    REPORTICONS:require('../assets/icons/report.png'),
    SETTINGSICON:require('../assets/icons/settings.png'),
    ITEMSICON:require('../assets/icons/items.png'),
    ITEMGROUPSICON:require('../assets/icons/itemsGroups.png'),
    CUSTOMERSICON:require('../assets/icons/customer.png'),
    VENDORSICON:require('../assets/icons/vendor.png'),
    ACCOUNTGROUPICON:require('../assets/icons/accountGroup.png'),
    SALESICON:require('../assets/icons/sales.png'),
    ROLESICON:require('../assets/icons/roles.png'),
    USERSICON:require('../assets/icons/users.png'),
    USERACTIVITIESICON:require('../assets/icons/userActivity.png'),
    DATEPICKERICONS:require('../assets/icons/datePicker.png'),
    LOGOUTICON:require('../assets/icons/logout.png')
};
